name: flutter_internship_2024_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  dotenv: ^4.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  http: ^1.2.1
  material_design_icons_flutter: ^7.0.7296
  rename_app: ^1.3.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - .env
    - assets/images/icon.png
    - assets/images/icon_transparent.png
    - assets/images/libry.png
    - assets/Conversion_path.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#EFF5F3"
    theme_color: "#EFF5F3"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/images/icon.png"
